
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://github.com/anu24sri"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /anu24sri.github.com

# Google tracking id

google-tracking-id: "UA-70072021-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Anupriya Srivastava"
title: "Life Voyage"
description: "Anupriya's mindspace"
keywords: "anupriya, electronics, fashion, technology, personal, blog"
favicon: "/img/chip.ico"

################
# Header layout #
################

black-favicon: "/img/chip.ico"

background-img: "/img/backgroundme.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Everyone's got the same story -- we just got different details."
  - text: "You never arrive."
  - text: "Inspiration is for amateurs. Everyone else goes to work"
  - text: "Life is like riding a bicycle. To keep your balance you must keep moving."
  - text: "Success = f(work)"
  - text: "Everything is figure-out-able"
  - text: "24*7*365. Always. Forever."
  - text: "Hard Work Vs Regret"
  - text: "How you do anything is how you do everything."
  - text: "What seems hard now, will one day be your warmup."

me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "green"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 7

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "anu24sri"

syntax-highlight: True

############
# Timeline #
############

events:

  - image: "/img/timeline/220px-DTU,_Delhi_official_logo.png"
    date: "Aug 2019 - Present"
    description: "Masters in VLSI" 

  - image: "/img/timeline/drdo.jpg"
    date: "May 2017 - July 2017"
    description: "Summer research Intern at DRDO Solid State Physics Lab" 

  - image: "/img/timeline/DU.png"
    date: "Oct 2016 - Dec 2016"
    description: " Research intern at University of Delhi, Department of Physics and Astrophysics" 

  - image: "/img/timeline/electronics-and-communication-courses.jpg"
    date: "July 2014"
    description: "Started my electronics journey"

  

# First image of the Timeline

timeline-img: "/img/timeline.jpg"

###########
# Contact #
###########

email: "anupriya51srivastava@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Anupriya is an awesome person."
author_blurb_image: "/img/me.jpg"

##################
# Social Buttons #
##################


  

       
############
# 404 page #
############

404_img: "/img/404.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post' 
  Timeline: 'timeline'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

# gems:
  # - jekyll-paginate
  # - jemoji

plugins:
  - jekyll-feed
  - jekyll-paginate
